### ISSUE TITLE
Can i use this for dogecoin?

### ISSUE THREAD

**Issue by buzztiaan** [micro-bitcoin/uBitcoin#12]
Heya, as dogecoin uses 99% the same stuff as bitcoin, it should, right?

**Comment by buzztiaan** [comment]
I guess this stuff all needs other constants, at least ; https://github.com/micro-bitcoin/uBitcoin/blob/master/src/Bitcoin.cpp#L19

but anything else?

**Comment by stepansnigirev** [comment]
I am not 100% sure, I think it should be just the constants, so you can fork the repo and change the constants to work with Doge or Litecoin or any other Bitcoin fork.

**Comment by buzztiaan** [comment]
Seems it works :) https://github.com/micro-bitcoin/uBitcoin/pull/13
