### ISSUE TITLE
Version 0.2.0 is not available at Platformio

### ISSUE THREAD

**Issue by ktecho** [micro-bitcoin/uBitcoin#27]
Last version available is 0.1.2 which is very old.

**Comment by BitMaker-hub** [comment]
Hi Luis, did you tried adding the github repo directly to lib_deps on platform.ini?
This should use last release version

```
lib_deps  = 
	https://github.com/micro-bitcoin/uBitcoin.git
```

**Comment by ktecho** [comment]
> Hi Luis, did you tried adding the github repo directly to lib_deps on platform.ini? This should use last release version
> 
> ```
> lib_deps  = 
> 	https://github.com/micro-bitcoin/uBitcoin.git
> ```

Yes, the thing is that I added the dependencies to this project for the same versions as in the Arduino library, so they're installed automatically when installing the library, and it failed because uBitcoin 0.2 was not present:

https://github.com/lnbits/arduino-nostr/pull/8

I wonder if  I can specify the github repo as a dependency...

**Comment by blackcoffeexbt** [comment]
I'll ask Stepan if he can push 0.2.0 to platform.io

**Comment by blackcoffeexbt** [comment]
ty for the PR btw, as soon as uBitcoin 0.2.0 is on the platform.io registry, let's get this PR merged!

**Comment by stepansnigirev** [comment]
Updated the library on platformio to v0.2.0
