### ISSUE TITLE
uBitcoin/src/BaseClasses.cpp:3:10: fatal error: cstdlib: No such file or directory

### ISSUE THREAD

**Issue by FeatureSpitter** [micro-bitcoin/uBitcoin#30]
I installed this library using the visual studio code Arduino extension (by Microsoft). And I am getting this error when compiling:

![image](https://github.com/micro-bitcoin/uBitcoin/assets/39516190/c68a6040-3df9-4615-9a81-070c34edfe64)

```
[Starting] Verifying sketch 'arduino-wallet.ino'
[Warning] Output path is not specified. Unable to reuse previously compiled files. Build will be slower. See README.
/home/nemewsys/Arduino/libraries/uBitcoin/src/BaseClasses.cpp:3:10: fatal error: cstdlib: No such file or directory
 #include <cstdlib>
          ^~~~~~~~~
compilation terminated.

Error during build: exit status 1
```

All the other libs seem to work fine, this one is the exception.

Do I need to make anything additional to have this working with VS Code?

Thanks!

**Comment by FeatureSpitter** [comment]
@stepansnigirev

**Comment by FeatureSpitter** [comment]
I get the same error in the IDE it seems:

![image](https://github.com/micro-bitcoin/uBitcoin/assets/39516190/019cb64e-d28e-4f70-9211-f8d4d974348f)

I am using the latest version of the IDE, the latest version of uBitcoin and Ubuntu 22:

Linux nemewsys-82JU 6.2.0-34-generic #34-Ubuntu SMP PREEMPT_DYNAMIC Mon Sep  4 13:06:55 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tinygiant** [comment]
How was this resolved? I'm seeing the same thing on a windows 10 pc.
