### ISSUE TITLE
The library isn't listed on the PlatformIO

### ISSUE THREAD

**Issue by phplego** [micro-bitcoin/uBitcoin#8]
Thank you for great job and this polished lib! It would be nice if we could download this lib as dependency in PlatformIO project. Thanks

**Comment by stepansnigirev** [comment]
Good idea :)
I'll try to find out how to get listed in PlatformIO and arduino libraries list.

**Comment by phplego** [comment]
As I understand author have to install PlatformIO to be able to run `pio` command. Then add library.json to the root of the project directory (at the same level as src dir). 

And then execute `publish` command:
```
pio package publish [<source directory, tar.gz or zip>]
```

https://docs.platformio.org/en/latest/librarymanager/creating.html#publishing

**Comment by stepansnigirev** [comment]
https://platformio.org/lib/show/11650/uBitcoin
